apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentmng-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentmng
  template:
    metadata:
      labels:
        app: studentmng
    spec:
      containers:
        - name: studentmng
          image: jenkinspipeline
          imagePullPolicy: Never
          ports:
            - containerPort: 3000